#!/usr/bin/env bash

echo "run intellij"
function delayedPluginInstall {
    echo "copying plugins & configs into home folder"
    cp -r /home/freshinstall/.IdeaIC15 /home/developer
}

if [ ! -d /home/developer/.IdeaIC15/config/plugins/Go ]; then
    # We are running with a non-Docker contained volume for IntelliJ prefs so we need to setup the plugin again
    delayedPluginInstall
fi

sudo chown developer:developer -R /home/developer

sudo /etc/setproxyforaptget.sh

exec /opt/intellij/bin/idea.sh
